In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('data.csv')

In [5]:
df.sample(10)

,Order ID,Total Amount,Created At,Status,Rider Name,Rider Contact,Delivery Status,Expected ETA,Delay Reason,Scheduled Date,Scheduled Time,Packing Duration,Picked Up Duration,Out for Delivery Duration,Reached Delivery Duration,Reached Delivery Timestamp,Delivered Duration,Delivered Timestamp
1283,#17051,-,22 Jun 26 21:41,delivered,Unassigned,-,Delayed (+1605 mins),53 minutes,Marked as delivered manually,23/06/2026,15:00,-,-,-,-,-,-,24 Jun 26 18:45
117,#18284,-,30 Jun 26 13:31,delivered,Arun Evrecahrge,9368619708,On-Time,29 minutes,-,-,-,1m,4m,0m,14m,30 Jun 26 13:52,8m,30 Jun 26 14:00
7358,#15251,-,12 Jun 26 09:09,cancelled,Sagar Poddar,8750966039,On-Time,60 minutes,customer door step,-,-,1m,2m,0m,32m,12 Jun 26 09:45,-,-
5873,#16798,-,21 Jun 26 12:46,delivered,Tushar EvRecharge,8791327565,On-Time,62 minutes,-,-,-,1m,3m,7m,21m,21 Jun 26 13:19,2m,21 Jun 26 13:22
2146,#16124,-,17 Jun 26 23:00,delivered,ashutosh sfx,7838403436,On-Time,27 minutes,-,-,-,1m,3m,3m,9m,17 Jun 26 23:18,6m,17 Jun 26 23:24
6121,#16545,-,19 Jun 26 23:09,delivered,lakhan singh,9990083896,On-Time,52 minutes,-,-,-,1m,4m,1m,24m,19 Jun 26 23:43,5m,19 Jun 26 23:48
6490,#16142,-,18 Jun 26 08:08,delivered,ajay pratap singh Kiddo,9412777140,On-Time,32 minutes,-,-,-,0m,3m,0m,12m,18 Jun 26 08:25,4m,18 Jun 26 08:29
699,#17687,-,26 Jun 26 14:03,delivered,AKASH THAKURSFX,9576234127,On-Time,57 minutes,-,-,-,1m,6m,1m,28m,26 Jun 26 14:41,8m,26 Jun 26 14:50
8147,#14458,-,05 Jun 26 18:06,reached_delivery,SONU SFX,8595492226,On-Time,61 minutes,-,-,-,1m,2m,0m,9m,05 Jun 26 18:20,-,-
5540,#17166,-,23 Jun 26 18:23,delivered,Shakir Khan,8588821385,On-Time,34 minutes,-,-,-,1m,2m,0m,2m,23 Jun 26 18:31,38m,23 Jun 26 19:09

In [6]:
df.shape

(8717, 18)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8717 entries, 0 to 8716
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Order ID                    8717 non-null   object
 1   Total Amount                8717 non-null   object
 2   Created At                  8717 non-null   object
 3   Status                      8717 non-null   object
 4   Rider Name                  8717 non-null   object
 5   Rider Contact               8717 non-null   object
 6   Delivery Status             8717 non-null   object
 7   Expected ETA                8717 non-null   object
 8   Delay Reason                8697 non-null   object
 9   Scheduled Date              8717 non-null   object
 10  Scheduled Time              8717 non-null   object
 11  Packing Duration            8717 non-null   object
 12  Picked Up Duration          8717 non-null   object
 13  Out for Delivery Duration   8717 non-null   object
 14  Reached Delivery Duration   8717 non-null   object
 15  Reached Delivery Timestamp  8717 non-null   object
 16  Delivered Duration          8717 non-null   object
 17  Delivered Timestamp         8717 non-null   object
dtypes: object(18)
memory usage: 1.2+ MB

In [8]:
df.describe()

,Order ID,Total Amount,Created At,Status,Rider Name,Rider Contact,Delivery Status,Expected ETA,Delay Reason,Scheduled Date,Scheduled Time,Packing Duration,Picked Up Duration,Out for Delivery Duration,Reached Delivery Duration,Reached Delivery Timestamp,Delivered Duration,Delivered Timestamp
count,8717,8717,8717,8717,8717,8717,8717,8717,8697,8717,8717,8717,8717,8717,8717,8717,8717,8717
unique,4359,2,4037,12,179,181,622,91,466,35,20,287,253,54,137,3486,173,3450
top,#18405,-,20 Jun 26 14:07,delivered,Unassigned,-,On-Time,33 minutes,-,-,-,1m,2m,0m,-,-,-,-
freq,2,8716,8,7424,846,846,5640,320,6376,7564,7564,2116,1520,3762,2230,1230,1576,1268

In [9]:
df.isnull().sum()

Order ID                       0
Total Amount                   0
Created At                     0
Status                         0
Rider Name                     0
Rider Contact                  0
Delivery Status                0
Expected ETA                   0
Delay Reason                  20
Scheduled Date                 0
Scheduled Time                 0
Packing Duration               0
Picked Up Duration             0
Out for Delivery Duration      0
Reached Delivery Duration      0
Reached Delivery Timestamp     0
Delivered Duration             0
Delivered Timestamp            0
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(4358)

In [11]:
df[df['Order ID'].duplicated()]

,Order ID,Total Amount,Created At,Status,Rider Name,Rider Contact,Delivery Status,Expected ETA,Delay Reason,Scheduled Date,Scheduled Time,Packing Duration,Picked Up Duration,Out for Delivery Duration,Reached Delivery Duration,Reached Delivery Timestamp,Delivered Duration,Delivered Timestamp
4359,#18405,-,30 Jun 26 23:59,cancelled,Unassigned,-,Delayed (+3783 mins),49 minutes,Item NA at store,-,-,-,-,-,-,-,-,-
4360,#18404,-,30 Jun 26 23:54,delivered,sandeep Kiddo,8057924668,Delayed (+4 mins),60 minutes,-,-,-,0m,3m,0m,1h 0m,01 Jul 26 00:58,0m,01 Jul 26 00:59
4361,#18403,-,30 Jun 26 23:54,delivered,Robin SFX,7982753727,On-Time,60 minutes,-,01/07/2026,12:00,3h 2m,8h 7m,-,-,01 Jul 26 11:41,0m,01 Jul 26 11:42
4362,#18402,-,30 Jun 26 23:53,delivered,ROSHAN KUMARSFX,8423838078,Delayed (+10 mins),49 minutes,rider not avilabile,01/07/2026,07:00,3h 6m,4h 38m,3m,29m,01 Jul 26 08:10,5m,01 Jul 26 08:16
4363,#18401,-,30 Jun 26 23:51,delivered,AKASH THAKURSFX,9576234127,On-Time,53 minutes,-,01/07/2026,10:00,3h 10m,6h 18m,18m,12m,01 Jul 26 09:51,9m,01 Jul 26 10:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8712,#13892,-,01 Jun 26 07:26,packed,Unassigned,-,Delayed (+46530 mins),55 minutes,-,-,-,20m,-,-,-,-,-,-
8713,#13891,-,01 Jun 26 07:01,out_for_delivery,Sanjay Kumar,7011471439,Delayed (+46557 mins),53 minutes,-,-,-,1m,16m,0m,-,-,-,-
8714,#13890,-,01 Jun 26 06:46,delivered,Vikas Kumar,9953586174,Delayed (+45 mins),49 minutes,-,-,-,4m,33m,28m,28m,01 Jun 26 08:20,8m,01 Jun 26 08:28
8715,#13889,-,01 Jun 26 06:26,delivered,sandeep Kiddo,8057924668,Delayed (+5 mins),45 minutes,-,-,-,4m,11m,-,-,01 Jun 26 07:17,6m,01 Jun 26 07:23
8716,#13888,-,01 Jun 26 00:09,delivered,sandeep Kiddo,8057924668,Delayed (+6 mins),51 minutes,-,-,-,4m,0m,0m,51m,01 Jun 26 01:06,1m,01 Jun 26 01:08

In [12]:
df['Order ID'].nunique()

4359

In [13]:
df[df['Order ID']=='#18402']

,Order ID,Total Amount,Created At,Status,Rider Name,Rider Contact,Delivery Status,Expected ETA,Delay Reason,Scheduled Date,Scheduled Time,Packing Duration,Picked Up Duration,Out for Delivery Duration,Reached Delivery Duration,Reached Delivery Timestamp,Delivered Duration,Delivered Timestamp
3,#18402,-,30 Jun 26 23:53,delivered,ROSHAN KUMARSFX,8423838078,Delayed (+10 mins),49 minutes,rider not avilabile,01/07/2026,07:00,3h 6m,4h 38m,3m,29m,01 Jul 26 08:10,5m,01 Jul 26 08:16
4362,#18402,-,30 Jun 26 23:53,delivered,ROSHAN KUMARSFX,8423838078,Delayed (+10 mins),49 minutes,rider not avilabile,01/07/2026,07:00,3h 6m,4h 38m,3m,29m,01 Jul 26 08:10,5m,01 Jul 26 08:16

In [14]:
df_final=df.drop_duplicates(keep='first')

In [15]:
df_final.duplicated().sum()

np.int64(0)

In [16]:
df_final.drop(df_final[df_final['Delay Reason'] == 'Test order'].index, inplace=True)

/var/folders/md/bl7d8ffd71j23r2c46ylgpxm0000gn/T/ipykernel_8835/1085505269.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.drop(df_final[df_final['Delay Reason'] == 'Test order'].index, inplace=True)

In [17]:
df_final.drop(df_final[df_final['Status'] == 'cancelled'].index, inplace=True)

/var/folders/md/bl7d8ffd71j23r2c46ylgpxm0000gn/T/ipykernel_8835/4053095564.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.drop(df_final[df_final['Status'] == 'cancelled'].index, inplace=True)

In [18]:
df_final.drop(df_final[df_final['Expected ETA'] == '-'].index, inplace=True)

/var/folders/md/bl7d8ffd71j23r2c46ylgpxm0000gn/T/ipykernel_8835/1710040942.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.drop(df_final[df_final['Expected ETA'] == '-'].index, inplace=True)

In [19]:
df_final.drop(df_final[df_final['Order ID'] == 'Order ID'].index, inplace=True)

/var/folders/md/bl7d8ffd71j23r2c46ylgpxm0000gn/T/ipykernel_8835/1284109224.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.drop(df_final[df_final['Order ID'] == 'Order ID'].index, inplace=True)

In [20]:
df_final.drop(df_final[df_final['Delivered Timestamp']=='-'].index, inplace=True)

/var/folders/md/bl7d8ffd71j23r2c46ylgpxm0000gn/T/ipykernel_8835/574673338.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_final.drop(df_final[df_final['Delivered Timestamp']=='-'].index, inplace=True)

In [21]:
df_final

,Order ID,Total Amount,Created At,Status,Rider Name,Rider Contact,Delivery Status,Expected ETA,Delay Reason,Scheduled Date,Scheduled Time,Packing Duration,Picked Up Duration,Out for Delivery Duration,Reached Delivery Duration,Reached Delivery Timestamp,Delivered Duration,Delivered Timestamp
1,#18404,-,30 Jun 26 23:54,delivered,sandeep Kiddo,8057924668,Delayed (+4 mins),60 minutes,-,-,-,0m,3m,0m,1h 0m,01 Jul 26 00:58,0m,01 Jul 26 00:59
2,#18403,-,30 Jun 26 23:54,delivered,Robin SFX,7982753727,On-Time,60 minutes,-,01/07/2026,12:00,3h 2m,8h 7m,-,-,01 Jul 26 11:41,0m,01 Jul 26 11:42
3,#18402,-,30 Jun 26 23:53,delivered,ROSHAN KUMARSFX,8423838078,Delayed (+10 mins),49 minutes,rider not avilabile,01/07/2026,07:00,3h 6m,4h 38m,3m,29m,01 Jul 26 08:10,5m,01 Jul 26 08:16
4,#18401,-,30 Jun 26 23:51,delivered,AKASH THAKURSFX,9576234127,On-Time,53 minutes,-,01/07/2026,10:00,3h 10m,6h 18m,18m,12m,01 Jul 26 09:51,9m,01 Jul 26 10:01
6,#18399,-,30 Jun 26 23:48,delivered,sandeep Kiddo,8057924668,On-Time,60 minutes,-,-,-,0m,4m,0m,28m,01 Jul 26 00:22,34m,01 Jul 26 00:57
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4349,#13896,-,01 Jun 26 08:28,delivered,ABHIJEET SFX,9811808152,On-Time,34 minutes,-,-,-,1m,6m,-,-,01 Jun 26 08:36,24m,01 Jun 26 09:00
4350,#13895,-,01 Jun 26 07:33,delivered,PAWAN SHARMA,8527857830,On-Time,28 minutes,-,-,-,2m,1m,1m,7m,01 Jun 26 07:47,15m,01 Jun 26 08:02
4355,#13890,-,01 Jun 26 06:46,delivered,Vikas Kumar,9953586174,Delayed (+45 mins),49 minutes,-,-,-,4m,33m,28m,28m,01 Jun 26 08:20,8m,01 Jun 26 08:28
4356,#13889,-,01 Jun 26 06:26,delivered,sandeep Kiddo,8057924668,Delayed (+5 mins),45 minutes,-,-,-,4m,11m,-,-,01 Jun 26 07:17,6m,01 Jun 26 07:23
4357,#13888,-,01 Jun 26 00:09,delivered,sandeep Kiddo,8057924668,Delayed (+6 mins),51 minutes,-,-,-,4m,0m,0m,51m,01 Jun 26 01:06,1m,01 Jun 26 01:08

In [22]:
df_final.to_csv('data_cleaned.csv',index=False)